# Removed obsolete version attribute

services:
  daasr-middleware:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DAASR_BASE_RATE_LIMIT=100
      - DAASR_MIN_RATE_LIMIT=10
      - DAASR_MAX_RATE_LIMIT=1000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for distributed rate limiting
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

# Keep volumes section but add enterprise-ready configurations
volumes:
  redis_data:
    driver_opts:
      type: local
      o: bind
      device: "/mnt/c/Users/muham/OneDrive/Desktop/Projekan Betul/website-enterprise/redis-data"
